# Generated by Django 2.2 on 2020-06-24 04:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200615_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(related_name='siguiendo_user', through='users.Seguidor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='seguidores',
            field=models.ManyToManyField(related_name='seguidores_user', through='users.Seguidor', to=settings.AUTH_USER_MODEL),
        ),
    ]
